name: PR Assistant
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  relgen:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: zlalvani/relgen@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          llm-key: ${{ secrets.OPENAI_API_KEY }}
          llm-provider: openai
          llm-model: gpt-4o-mini
          # Optional customizations:
          # description-template: .github/templates/pr-description.md
          # description-prompt: .github/prompts/pr-description.txt
          # write-mode: comment  # or 'pr' to update PR description
          # label-mode: add     # or 'set' to replace existing labels
