name: Type Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Build
        run: pnpm turbo build

      - name: Run type check
        run: pnpm typecheck
