name: verify version of relgen cli
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths:
      - "packages/relgen-core/**"

jobs:
  verify-version:
    runs-on: ubuntu-latest
    steps:
      # get main version
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: martinbeentjes/npm-get-version-action@main
        with:
          path: packages/relgen-core
        id: main-version

      # get pr version
      - uses: actions/checkout@v4
      - uses: martinbeentjes/npm-get-version-action@main
        with:
          path: packages/relgen-core
        id: pr-version

      - name: Setup
        uses: ./tooling/github/setup

      - uses: actions/github-script@v6
        env:
          PR_VERSION: ${{steps.pr-version.outputs.current-version}}
          MAIN_VERSION: ${{steps.main-version.outputs.current-version}}
        with:
          script: |
            require('./.github/versioning.js').verify({ github, context, core, target: 'core' })